### ISSUE TITLE
Unable to define the custom xmlns

### ISSUE THREAD

**Issue by rajivraghu** [DinoChiesa/ApigeeEdge-Java-Xpath#1]
Hi Dino,
I got a scenario where i need to define custom **xmlns**  . The xpath doesnot resolve. 

Sample XML. 
`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://eventtrigger.webservice.alerts.ctp.stp.com">
<Parameter>
<ordinal>4</ordinal>
<value>1647622651000</value>
</Parameter>
</soap:Envelope>
`
Apigee Xpath Policy ..
`<JavaCallout async="false" continueOnError="false" enabled="true" name="Java_XPath">
    <DisplayName>Java_XPath</DisplayName>
    <Properties>
        <Property name="source">message.content</Property>
         <Property name="xmlns:soap">http://schemas.xmlsoap.org/soap/envelope/</Property>
        <Property name="xpath:rcn">/soap:Envelope/Parameter/ordinal</Property>
    </Properties>
    <ClassName>com.google.apigee.callouts.ExtractXpath</ClassName>
    <ResourceURL>java://apigee-xpath-20210409.jar</ResourceURL>
</JavaCallout>`

This fails with ... 

**xpath_error 	xpath does not resolve to one node. (length=0)	
xpath_exception 	java.lang.IllegalStateException: xpath does not resolve to one node. (length=0)**

But, 
If i remove **xmls** from my XML as below, The xpath works fine. 

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" >
<Parameter>
<ordinal>4</ordinal>
<value>1647622651000</value>
</Parameter>
</soap:Envelope>`

How do i resolve this ?

**Comment by DinoChiesa** [comment]
I think you want this
```
<JavaCallout  name="Java_XPath">
  <DisplayName>Java_XPath</DisplayName>
  <Properties>
    <Property name="source">message.content</Property>
    <Property name="xmlns:soap">http://schemas.xmlsoap.org/soap/envelope/</Property> 
    <!-- specify a namespace and assign a prefix , so you can refer to it later, in the xpath -->
    <Property name="xmlns:ns1">http://eventtrigger.webservice.alerts.ctp.stp.com</Property>
    <!-- to refer to the Parameter and the ordinal elements, include the ns1 prefix --> 
    <Property name="xpath:rcn">/soap:Envelope/ns1:Parameter/ns1:ordinal/text()</Property>
  </Properties>
  <ClassName>com.google.apigee.callouts.ExtractXpath</ClassName>
  <ResourceURL>java://apigee-xpath-20210409.jar</ResourceURL>
</JavaCallout>
```

The `xmlns=` attribute in your XML document specifies the default namespace. Because the `<Parameter>` element has no XML namespace explicitly declared, it inherits the default namespace of its parent element.  That namespace is `http://eventtrigger.webservice.alerts.ctp.stp.com`. Likewise the `<ordinal>` element has no `xmlns=` attribute, so it inherits the namespace from the default namespace of _its_ parent. 

Therefore, to specify an xpath that matches the Parameter element, you need to specify the namespace. Do that via a prefix that you define. The prefix in the xpath does not have to match a prefix in the XML document. In fact the document might not have a prefix at all, as in this case. 

This is just one of those quirks of XML, Namespaces and their prefixes, and Xpath.

**Comment by DinoChiesa** [comment]
I'm going to close this one as answered & resolved.
